### PR TITLE
Support New Business Products

### PR DESCRIPTION
**Pull request by aitzkovitz**

### CODE REVIEW

**Review by mmoghaddam385 — COMMENTED** [review]
LGTM, are you planning on releasing this or is there more to add? Don't forget to update the version before releasing: https://github.com/polygon-io/client-jvm#notes-for-maintainers

**Review by morningvera — APPROVED** [review]
lgtm

**Comment by aitzkovitz** [comment]
> LGTM, are you planning on releasing this or is there more to add? Don't forget to update the version before releasing: https://github.com/polygon-io/client-jvm#notes-for-maintainers

good call. Do i need to manually release to maven using that gradle task?

**Comment by mmoghaddam385** [comment]
> > LGTM, are you planning on releasing this or is there more to add? Don't forget to update the version before releasing: https://github.com/polygon-io/client-jvm#notes-for-maintainers
> 
> good call. Do i need to manually release to maven using that gradle task?

@aitzkovitz no you don't need to do anything special, updating the version in code there is just so the user agent is accurate. When you create a Github release you should see the new version appear on [jitpack](https://jitpack.io/#polygon-io/client-jvm) pretty quickly

**Pull request merged**
