### PR TITLE
Added rest examples for stocks, options, indices, forex, and crypto

### PR DESCRIPTION
**Pull request by justinpolygon**
Working on flushing out the examples here. There are still some issues to be resolved and I'm working on it.

This also depends on the following:
- https://github.com/polygon-io/client-jvm/pull/110
- https://github.com/polygon-io/client-jvm/pull/112
- https://github.com/polygon-io/client-jvm/pull/113
- Adding options websocket code

### CODE REVIEW

**Comment by justinpolygon** [comment]
Hey @mmoghaddam385, wanted to get some feedback here. I wanted to add rest/websocket examples for everything and was thinking about how to logical split that up. I've come up with this but wanted to get your thought. My thinking, is that people can turn on and off things via the KotlinSample app, run gradlew, test things out, and if they want the code they can go into the specific examples.

**Comment by mmoghaddam385** [comment]
> Hey @mmoghaddam385, wanted to get some feedback here. I wanted to add rest/websocket examples for everything and was thinking about how to logical split that up. I've come up with this but wanted to get your thought. My thinking, is that people can turn on and off things via the KotlinSample app, run gradlew, test things out, and if they want the code they can go into the specific examples.

This seems like a good plan, I like separating the examples out into their own files 👍

**Comment by justinpolygon** [comment]
> > Hey @mmoghaddam385, wanted to get some feedback here. I wanted to add rest/websocket examples for everything and was thinking about how to logical split that up. I've come up with this but wanted to get your thought. My thinking, is that people can turn on and off things via the KotlinSample app, run gradlew, test things out, and if they want the code they can go into the specific examples.
> 
> This seems like a good plan, I like separating the examples out into their own files 👍

Perfect, thank you. I'll flush this out.

**Review by mmoghaddam385 — APPROVED** [review]
LGTM

**Pull request merged**
